#!/bin/bash

echo "Welcome to gq_build!"

if [ ! "$#" -ge 1 ]; then
	echo "  usage: gq_build <productName> <optional arguments ...>"
	echo "    optional arguments are:"
	echo "       --gqreplace (replaces / overwrites iOS product files)"
	exit 1
fi

# filter out the first agruments and forward only the optional additional arguments to unity:
inArgs=($@)
forwardArgs=()
for i in "${!inArgs[@]}"; do
	if [ $i -gt 0 ]; then
		forwardArgs+=(${inArgs[$i]})
	fi
done

# TODO: read project path from environment variable
projectPath=/Users/muegge/projects/qv-geoquest/GQUnityClient

# TODO: check that given product name is valid, i.e. folder exists and minimal requirements for product

# TODO: copy associated config file into streaming assets folder of unity project

# Splash screen image is copied into place:
productSplash=$projectPath/Production/products/${1}/resources/splash.jpg
if [ ! -f "$productSplash" ]; then
	echo "ERROR:  I'm missing the splashscreen file for your product."
	echo "  Please provide it at: $productSplash"
	echo "Build failed.\n"
	exit 1
fi 
splashPlaceholder=$projectPath/Assets/Generated/splash.jpg
if [ ! -f "$splashPlaceholder" ]; then
	echo "ERROR:  Splash screen placeholder is missing: $splashPlaceholder"
	echo "Build failed.\n"
	exit 1
fi 
cp $projectPath/Production/products/${1}/resources/splash.jpg $projectPath/Assets/Generated/splash.jpg
# TODO check that splash screen image for product exists, otherwise use default and issue warning.

# Build Android project:
/Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode \
	-projectPath $projectPath  \
	-executeMethod Product.Builder.BuildPlayers \
	--gqproduct $1 $forwardArgs
ret_code=$?

# TODO: check whether build successful
if [ $ret_code != 0 ]; then
	printf "Build ERROR : [%d]\n\n" $ret_cod
# TODO: build failed, we should open editor.log file
  
  	exit $ret_code
else
	printf "Build succeeded.\n"
fi

# TODO: store build with version number in versions folder (android and iOS seprarately)

# TODO build (and append?) iOS project